services:
  postgres:
    container_name: postgres_sql_bsn
    image: postgres
    environment:
      POSTGRES_USER: nazat
      POSTGRES_PASSWORD: agent47
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - bsn
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  bsn-api:
    container_name: bsn-api
    image: nazatmustag/bsn:1.0.0
    ports:
      - 9000:9000
    networks:
      - bsn
    depends_on:
      - postgres
networks:
  bsn:
    driver: bridge
volumes:
  postgres:
    driver: local